#!/bin/sh

docker build\
    --build-arg OPENVAS_VERSION=20.8.1 \
    --build-arg VERSION=1.1 \
    --build-arg GVM_LIBS_VERSION=20.8.1 \
    --build-arg GOCROND_VERSION=0.6.1 \
    --build-arg ARCH=64 \
    -f $DOCKERFILE_PATH \
    -t $IMAGE_NAME .
