#!/bin/sh

redis-server /etc/redis/redis-openvas.conf &&\
[ ! -d /usr/var/lib/gvm/CA ] && gvm-manage-certs -a;
[ -f /var/run/openvas.pid ] && rm /var/run/openvas.pid;
ospd-openvas -p ${PORT} &
sleep 20 && greenbone-nvt-sync &&\
[ -z NOT_CROND ] && go-crond --run-parts-daily=greenbone-nvt-sync &
sleep 30 && tail -f /usr/local/var/log/gvm/openvas.log
